---
# This is still broken on Ubuntu 12.04. Need to use a Fedora Docker container
sudo: required
language: python
branches:
  only:
    - stable
install:
  - sudo apt-get install gfortran
  - pip install -U pytest==2.7.2 setuptools==18.3.1 pip==7.1.2
  - pip install -r requirements.txt
script:
  - python setup.py pkdeploy
